### Booking room
POST http://localhost:8080/api/create HTTP/1.1 
Content-Type: application/json

{ 
  "Booking_Description" : "",
  "Booking_Status": "Reserved",
  "Booking_date": "06/11/2023",
  "Booking_period": "10:30 - 12:20",
  "Booking_for" : "CPE334", 
  "Room_ID" : "KM5",
  "User_Email" : "Phongprawi.ratt@kmutt.ac.th",
  "User_1" : "nut",
  "User_2" : "fifa",
  "User_3" : "mesa",
  "User_4" : "kla",
  "User_5" : "beer",
  "User_6" : ""
}

### Get booking room status
POST http://localhost:8080/api/room HTTP/1.1 
Content-Type: application/json

{
  "Booking_date": "06/11/2023"
}  

### Login
POST http://localhost:8080/api/authen HTTP/1.1 
Content-Type: application/json

{
  "email" : "Jedsada_chai@kmutt.ac.th",
  "password": "secret123"
}

### List booking
POST  http://localhost:8080/api/list HTTP/1.1 
Content-Type: application/json

{
  "email": "Thanaton_puga@kmutt.ac.th"
}

### Delete booking
DELETE  http://localhost:8080/api/delete HTTP/1.1 
Content-Type: application/json

{
  "id": "Y0NJh2nDlT4bm3K6s4Ib"
}